#!/bin/bash
echo "═══════════════════════════════════════"
echo "  RAZOR TASK DASHBOARD"
echo "═══════════════════════════════════════"
echo ""
echo "📋 PENDING:"
ls -1 ~/razor-voice-service/tasks/pending/*.md 2>/dev/null || echo "  (none)"
echo ""
echo "🔄 ACTIVE:"
ls -1 ~/razor-voice-service/tasks/active/*.md 2>/dev/null || echo "  (none)"
echo ""
echo "✅ COMPLETE:"
ls -1 ~/razor-voice-service/tasks/complete/*.md 2>/dev/null | tail -5 || echo "  (none)"
echo ""
